### PR TITLE
Fix bug for miniupnpc > 1.6 & Add instructions for secp256k1 error & Add Travis support & Fix unused variable error

### PR DESCRIPTION
**Pull request by SherlockStd**
## Resolve the following error for user of miniupnpc > 1.6 :

```
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -DUSE_SECP256K1 -I/root/ION/ion/src -I/root/ION/ion/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/root/ION/ion/src/leveldb/include -I/root/ION/ion/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/net.d -o obj/net.o net.cpp
net.cpp: In function 'void ThreadMapPort()':
net.cpp:1153:74: error: invalid conversion from 'int*' to 'unsigned char' [-fpermissive]
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                          ^
net.cpp:1153:74: error: too few arguments to function 'UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)'
In file included from net.cpp:26:0:
/usr/include/miniupnpc/miniupnpc.h:62:1: note: declared here
 upnpDiscover(int delay, const char * multicastif,
 ^
make: *** [obj/net.o] Error 1
```

## Add instructions for secp256k1 error : 

```
key.cpp:17:23: fatal error: secp256k1.h: No such file or directory
 #include <secp256k1.h>
                       ^
compilation terminated.
make: *** [obj/key.o] Error 1
```

## Add Travis support :

Last build [here](https://travis-ci.org/ionomy/ion/builds/131534486) 

## Fix unused variable error : 

```
key.cpp:552:17: warning: unused variable ‘ret’ [-Wunused-variable]
         if (int ret = secp256k1_ecdsa_sign_compact(instance_of_csecp256k1.ctx, hash.begin(), &vchSig[1], begin(), secp256k1_nonce_function_rfc6979, NULL, &rec))
                 ^
```

### CODE REVIEW

**Comment by RdeWilde** [comment]
Awesome

**Comment by SherlockStd** [comment]
Thanks ;)

**Comment by SherlockStd** [comment]
Here's the original patch :

[https://github.com/bitcoin/bitcoin/commit/9f3e48e5219a09b5ddfd6883d1f0498910eff4b6.patch](https://github.com/bitcoin/bitcoin/commit/9f3e48e5219a09b5ddfd6883d1f0498910eff4b6.patch)

**Comment by IonomyGuy** [comment]
Fixes #2

**Comment by mitchellcash** [comment]
Yikes, this is far too messy :P 

Split different commits into their own branches and pull requests and then squash related commits in this branch

**Comment by IonomyGuy** [comment]
Like @mitchellcash Suggest Please Split this up into separate PR's the devs wont approve a pull in a Massive PR like this.

**Comment by IonomyGuy** [comment]
I am going to close this pull request while you break it into separate PR's

**Pull request closed without merging**
