### PR TITLE
GCC hardening for Ion-Qt

### PR DESCRIPTION
**Pull request by mitchellcash**
- Ion-Qt: add new GCC compiler hardening options
- Ion-Qt: remove unneeded "--param ssp-buffer-size=1" flag

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
@mitchellcash just out of curiosity are those hardening options used on any current/updated coins (commit is almost 4 years old I wonder how "valid" those options are for this case)

**Comment by mitchellcash** [comment]
@IngCr3at1on yes I believe they are still valid, although some rearranging of their location could be used (i.e. make linux-specific linker options linux and linker specific.) <-- that's a mouthful!

**Comment by IngCr3at1on** [comment]
Hahaha, nice one... Next question; are any of those flags known to cause issues when compiling with Clang (IE: require compiler checks)?

**Comment by RdeWilde** [comment]
We should put travis to use on that one ;-)

**Comment by IonomyGuy** [comment]
@mitchellcash Can you please fix Conflicts now.

**Comment by mitchellcash** [comment]
@IonomyGuy done

**Pull request merged**
