### PR TITLE
Fix two build warnings

### PR DESCRIPTION
**Pull request by SherlockStd**
Fix the two following errors : 

```
key.cpp: In member function ‘bool CKey::SignCompact(const uint256&, std::vector<unsigned char>&) const’:
key.cpp:552:17: warning: unused variable ‘ret’ [-Wunused-variable]
         if (int ret = secp256k1_ecdsa_sign_compact(instance_of_csecp256k1.ctx, hash.begin(), &vchSig[1], begin(), secp256k1_nonce_function_rfc6979, NULL, &rec))
                 ^
```

```
key.cpp: In member function ‘bool CPubKey::VerifyCompact(const uint256&, const std::vector<unsigned char>&) const’:
key.cpp:632:10: warning: unused variable ‘fComp’ [-Wunused-variable]
     bool fComp = IsCompressed();
          ^

darksend.cpp: In member function ‘bool CDarkSendPool::IsCollateralValid(const CTransaction&)’:
darksend.cpp:978:29: warning: converting ‘false’ to pointer type ‘bool*’ [-Wconversion-null]
     bool* pfMissingInputs = false;
                             ^

darksend.cpp: In member function ‘void CDarkSendPool::SendDarksendDenominate(std::vector<CTxIn>&, std::vector<CTxOut>&, int64_t)’:
darksend.cpp:1160:58: warning: ‘pfMissingInputs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  if(!AcceptableInputs(mempool, tx, false, pfMissingInputs)){
                                                          ^

darksend.cpp: In function ‘void ProcessMessageDarksend(CNode*, std::string&, CDataStream&)’:
darksend.cpp:310:62: warning: ‘pfMissingInputs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
      if(!AcceptableInputs(mempool, tx, false, pfMissingInputs)){
                                                              ^

masternode.cpp: In function ‘void ProcessMessageMasternode(CNode*, std::string&, CDataStream&)’:
masternode.cpp:162:26: warning: converting ‘false’ to pointer type ‘bool*’ [-Wconversion-null]
  bool* pfMissingInputs = false;
                          ^

masternode.cpp: In member function ‘void CMasterNode::Check()’:
masternode.cpp:606:33: warning: converting ‘false’ to pointer type ‘bool*’ [-Wconversion-null]
         bool* pfMissingInputs = false;
                                 ^
```

### CODE REVIEW

**Comment by SherlockStd** [comment]
@RdeWilde very good job :+1:

**Comment by SherlockStd** [comment]
I verified [here](https://travis-ci.org/ionomy/ion/builds/131983248), any errors disappeared :smile:

**Comment by IonomyGuy** [comment]
@mitchellcash Opinion. I am waiting for Devs to look at this.

**Comment by SherlockStd** [comment]
@RdeWilde I already pull your commit about the unused variables here :smile:

**Comment by SherlockStd** [comment]
And also https://github.com/ionomy/ion/pull/28/commits/8c7e8c7efff0f4bab008ac8b10eae11c914cd8e2

**Comment by RdeWilde** [comment]
That's ok. I added it anyway because all my commits stack up somehow on every pull request. If i did not add them individually i would have seperate commits in my pr's with no pr attached. I thought i'd leave it up to the pro's.

What should I have done? Create feature branch from my master and reset to ionomy's HEAD and then cherry-pick a single commit - repeating for every PR?

**Comment by SherlockStd** [comment]
Yes exactly :+1:

I can do that for you with your commit :smile:

**Pull request merged**
