### PR TITLE
Fix Unused Variable

### PR DESCRIPTION
**Pull request by SherlockStd**
Woops, error ^^

### CODE REVIEW

**Comment by RdeWilde** [comment]
Check my repo for fix. Change to = NULL @SherlockStd

**Comment by SherlockStd** [comment]
Thanks :+1:

**Comment by SherlockStd** [comment]
I will patch this evening :smile:

**Comment by SherlockStd** [comment]
@RdeWilde Just a question, can you explain me why set to NULL instead of false ? Thanks ^^

**Comment by RdeWilde** [comment]
@SherlockStd Simple answer, no, Google told me :) Rest I did not understand. bool* = false is implicit conversion to null pointer or something.

**Pull request closed without merging**
