### PR TITLE
New Checkpoint

### PR DESCRIPTION
**Pull request by HyperCommNet**
Updated Checkpoint

### CODE REVIEW

**Comment by CeForce** [comment]
:+1:  From me.

**Comment by bradinator** [comment]
Looks good

**Comment by IngCr3at1on** [comment]
Not a checkpoint, master key for checkpoint server. I'm 99% certain this is forking code.

**Comment by CeForce** [comment]
Will be soft-fork only. users may see a checkpoint message, but upcoming releases will resolve the message.

**Comment by IngCr3at1on** [comment]
@CeForce last time I took the time to read the peercoin code (which is what that's from) invalid checkpoint keys causes a 24 hour peer ban.

**Pull request merged**
