### PR TITLE
Update to Fix DNSSEED

### PR DESCRIPTION
**Pull request by JSponaugle**
This should make it look a the hostname and not a direct ip.

### CODE REVIEW

**Comment by RdeWilde** [comment]
Let's get on with it :)

**Comment by mitchellcash** [comment]
Looks good, but probably wouldn't hurt to clean up the commits in this pull request before merging

**Comment by RdeWilde** [comment]
Please merge

**Comment by mitchellcash** [comment]
It might be my nervous tick, but I still feel before merging changes that we should be cleaning up these commits.

This realistically should have been one clean commit rather than three.

**Pull request merged**
