### PR TITLE
Update ion placeholder addresses

### PR DESCRIPTION
**Pull request by mitchellcash**

### CODE REVIEW

**Comment by IonomyGuy** [comment]
Dev's Are Verifying this. But it looks like a simple Fix.

**Comment by SherlockStd** [comment]
Wtf ?

**Comment by SherlockStd** [comment]
Why just change the e.g. adress ?

**Comment by IonomyGuy** [comment]
I don't understand your question?

**Comment by SherlockStd** [comment]
@IonomyGuy why update the placeholder adresses ?
Sorry if you don't understand me I'm french and I assume that my english isn't very good ^^

**Comment by IonomyGuy** [comment]
Based on the PR its just to keep everything uniform with ion it self.

**Comment by SherlockStd** [comment]
Ah ok

**Comment by mitchellcash** [comment]
@SherlockStd the reason to update it, is that the address that was being used prior to my change was an address that isn't part of the ion network. Obviously a leftover from the coin we forked the code from.

@IonomyGuy thanks for the merge :)

**Pull request merged**
