### PR TITLE
Add build-aux dir and .m4-files to secp256k

### PR DESCRIPTION
**Pull request by RdeWilde**
These files were copied from the Bitcoin repo as they were missing in the ION dist.

### CODE REVIEW

**Comment by RdeWilde** [comment]
I almost got it right, except that every commits seems to depend on the previous one, while there's no need for that..

**Comment by SherlockStd** [comment]
Yeah it's because you have pushed all comiits from the same branche on your repo (build-aux) ^^

**Comment by IngCr3at1on** [comment]
@RdeWilde yep, generally you want to check out a different working branch (from the master branch) for each different change that way they're all broken up nicely.

**Comment by RdeWilde** [comment]
So `git branch fresh-branch origin/master` and the `git cherry-pick <commit>`?

**Comment by mitchellcash** [comment]
@RdeWilde 
1. `git remote add upstream https://github.com/ionomy/ion.git`
2. `git fetch upstream`
3. `git checkout master`
4. `git reset --hard upstream/master --`
5. `git push origin +master`

Now that's out of the way:

1. `git checkout -b [name_of_your_new_branch]`
2. `git cherry-pick <commit id>` (Do this with however many commits are relevant)
3. `git push origin [name_of_your_new_branch]`
4. Open a new pull request :)

I think that covers it, I'm sure @IngCr3at1on will find something to poke a hole in!!

**Comment by IngCr3at1on** [comment]
@mitchellcash seems good, personally I try to make sure I always use ssh instead of http/https but that's not really relevant to the issue so much as me purposefully finding something to poke just because you said I would :P

**Comment by IonomyGuy** [comment]
Unable to Merge this PR

**Pull request closed without merging**
